ALTER TABLE groups_ ADD COLUMN IF NOT EXISTS avatar_url VARCHAR(512);
ALTER TABLE groups_ ADD COLUMN IF NOT EXISTS cover_url VARCHAR(512);
ALTER TABLE pages ADD COLUMN IF NOT EXISTS cover_url VARCHAR(512);
